// app/api/generate/route.ts
import { type NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { project_id, prompt, language, method, endpoint_path } = body

    console.log("Generate code request:", { project_id, prompt, language, method, endpoint_path })

    // Option 1: Return WebSocket URL with the specific format your component expects
    return NextResponse.json({
      websocket_url: `/api/v1/generate/stream${Date.now()}`,
      message: "Code generation started",
      status: "STARTED"
    })

    /* 
    // Option 2: Return direct response with code (uncomment if WebSocket isn't working)
    return NextResponse.json({
      code: `// Generated code for ${prompt}\n// Language: ${language}\n// Method: ${method}\n// Endpoint: ${endpoint_path}\n\nexport default function handler(req, res) {\n  // Your logic here\n  res.status(200).json({ success: true, message: "API endpoint generated by CodeBEGen" });\n}`,
      response: "I've generated the code based on your request.",
      message: "Code generated successfully",
      status: "COMPLETED"
    })
    */
  } catch (error) {
    console.error("Error generating code:", error)
    return NextResponse.json({
      error: "Failed to generate code",
      message: "An error occurred during code generation",
      status: "FAILED"
    }, { status: 500 })
  }
}