import React from 'react'
import { cn } from '~/utils'

const Terms = [
  {
    title: ' User Accounts',
    description: [
      'You may be required to create an account to access certain features of our Services',
      'You are responsible for maintaining the confidentiality of your account credentials',
      'You agree to provide accurate and complete information when creating your account',
      'You are responsible for all activities that occur under your account',
    ],
  },
  {
    title: 'Payment and Billing',
    description: [
      'We use Stripe to process payments for our Services.',
      'You agree to pay all fees and charges associated with your use of our Services as described on our website.',
      'All fees are non-refundable, except as expressly stated in our refund policy (if applicable).',
      'You are responsible for providing valid payment information.',
      'We reserve the right to change our pricing at any time. We will provide reasonable notice of any price changes.',
    ],
  },
  {
    title: 'Intellectual Property',
    description: [
      'Our Content: All content on our website, including text, graphics, logos, and software, is our property or the property of our licensors and is protected by intellectual property laws.  ',
      'User Generated Code: You retain ownership of the backend code generated using our Services. However, you grant us a non-exclusive, royalty-free license to use, reproduce, modify, and distribute your code for the purpose of providing and improving our Services.',
      'AI Generated Content: You understand that the AI generated code is generated by an algorithm, and may have limitations. We do not claim ownership of the underlying algorithms, but we do claim ownership of our specific implementation and user interface.',
    ],
  },
  {
    title: 'User Conduct',
    description: [
      'Use our Services for any illegal or unauthorized purpose.',
      'Transmit any viruses or other harmful code.',
      'Attempt to gain unauthorized access to our systems.',
      'Infringe on the intellectual property rights of others.',
      'Use our Services to create malicious or harmful software.',
      'Use our services to create code that violates any applicable laws or regulations.',
    ],
  },
  {
    title: ' Disclaimer of Warranties',
    description: [
      'Our Services are provided "as is" and "as available" without warranties of any kind, either express or implied.  ',
      'We do not warrant that our Services will be uninterrupted, error-free, or secure.',
      'We do not warrant the accuracy, completeness, or reliability of any code generated using our Services.',
      'We do not guarantee the performance of the generated code.',
      "We do not warrant the security of stripe's payment processor.",
    ],
  },
  {
    title: ' Limitation of Liability',
    description: [
      'In no event shall we be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your use of our Services.',
      'Our liability shall be limited to the amount you paid for our Services.',
      'We are not responsible for any loss or damage resulting from the use of code generated by our AI.',
    ],
  },
]

const TermsList = () => {
  return (
    <div className="mb-5">
      {Terms.map(({ title, description }) => (
        <div className="mb-5 flex flex-col gap-3" key={title}>
          <h3 className="text-[1.5rem] font-medium">{title}</h3>

          {title.toLowerCase() === 'user conduct' && (
            <ul className="pl-4 text-[1.5rem]">
              <li className="list-disc text-neutral-400 dark:text-white">
                You agree not to
              </li>
            </ul>
          )}
          <ul
            className={cn('pl-4', {
              'pl-8': title.toLowerCase() === 'user conduct',
            })}
          >
            {description.map((item) => (
              <li
                key={item}
                className={cn('list-disc pb-1 text-[1.5rem] text-neutral-300')}
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  )
}

export default TermsList
